### ISSUE TITLE
DFAssist not working through WTFast VPN

### ISSUE THREAD

**Issue by FoxyboiTia** [easly1989/ffxiv_act_dfassist#11]
Basically, when I load up the game through WTFast as a VPN service, DFassist no longer seems to work/run

Attached a log file here as well.

This works flawlessly without WTFast. Perhaps some sort of config/error?

![unknown (10)](https://user-images.githubusercontent.com/5994081/62836496-d8682980-bc63-11e9-9d6c-375523b29a2a.png)

**Comment by easly1989** [comment]
Already had this kind of issue, even if those were related to loopbacks
You are using latest version right?
Anyway now I'm on holiday, I'll be able to check for a possible solution only in a couple of weeks 😅

**Comment by sleepiebye** [comment]
Hullo just wondering if this ever got fixed?
