### ISSUE TITLE
Unable to show toast notification

### ISSUE THREAD

**Issue by dbimonsta** [easly1989/ffxiv_act_dfassist#12]
Getting these Error:

![toast](https://user-images.githubusercontent.com/54656609/63910017-562e8200-ca25-11e9-9990-92d96e6d2975.PNG)

any solutions?

**Comment by easly1989** [comment]
Access Denied.
what version of windows 10 are you running?
Are you using the x86 or x64 Advancend Combat Tracker executable?
Are you running ACT as Administrator?

(I"m working on a new release that will show system toast starting from Windows 8,and for all versione di of 10, but I have still some work to do on that!)

**Comment by easly1989** [comment]
Do you still have this problem with latest release?
