### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by gravis162** [easly1989/ffxiv_act_dfassist#18]
Since the new update of ACT and DFAssist i cant get dfassist to load. it throws errors no matter what i do. I did a clean reinstall of the program the plugin and everything, still the same stuff.

https://imgur.com/a/oHMI0sf

**Comment by easly1989** [comment]
I actually don't know why you are getting this.
Anyway, you may want to try latest release and report back. (2.0.3, removed filesystem logging, so no new file is written on the pc.. even though your problem seems related to something else..)

Let me know

**Comment by gravis162** [comment]
I disabled and removed dfassist then reinstalled it via the get plugins button in act, the version i downloaded had the 9/8 date on it, but i still get the same error

**Comment by easly1989** [comment]
Just tried to remove and add the plugin using the ACT get plugins button, and it did it without any problem at all (version 2.0.4)

I'm using latest version of Widows 10, latest version of ACT and running ACT as administrator.

You may want to try to download the plugin manually, and try Unblocking the dlls files once extracted to ensure that it works correctly.

Beside that, i dunno what to say;
I'll this issue open, but I need to find a way to reproduce the problem, otherwise it is difficult to fix it
sorry for the inconvenience :(

**Comment by gravis162** [comment]
Im not sure what can be causing it, but weird enough it affects me and my friends with the same issue. Ill try two reinstalls of act and the dfassist today. One ill do via Actor which installs act and a few plugins, i will also try just act and dfassist.  

Side note since your updates it would work upon first installing then stop after a dungeon or two and then upon restarting to program start throwing errors again. If there is anything i give you like logs or such let me know where/how and ill provide them.

**Comment by Vivi-Ornitier** [comment]
I have the same problem.

**Comment by easly1989** [comment]
Unfortunately, beside the logs of ACT itself (hoping it has anything useful in it)
there is not much we can look in to find a clue.

You may want to try and disable any other plugin besid FFXIV_Parsing plugin and DFAssist, and try again (maybe some other plugins are causing conflicts?)

**Comment by Vivi-Ornitier** [comment]
I reinstalled DFAssist only with the FFXIV_Parsing plugin, but the same problem occurs.
After reinstallation works fine, but restarting ACT causes the same problem and continues to occur afterwards.
I'm Japanese, so I use Google Translate. I'm sorry.

After reinstallation -> https://imgur.com/YsXCbw0
After ACT restarts  -> https://imgur.com/XWiQ67I

**Comment by easly1989** [comment]
[DFAssist_EarlyInitializeTest.zip](https://github.com/easly1989/ffxiv_act_dfassist/files/3601635/DFAssist_EarlyInitializeTest.zip)

Try this version.
This may not work at all, as it initializes the plugin variables (MainControl and PluginData) before the actual ACT mainform is loaded (so it is potentially dangerous).

The problem you are having may be related to a late initialization of the plugin; that was calling a method in a particular moment when (effectively) the _mainControl variable was never initialized.

If you test this release and it works ok, i'll push the fix and make an official 2.0.7 release 
Let me know! :)

**Comment by Vivi-Ornitier** [comment]
Thank you very much.
I restarted and entered the content several times, but it works fine for now.:laughing:

**Comment by easly1989** [comment]
Version 2.0.7 is exactly the same as the Test release I've uploaded in the previous post.
you can download it [here](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.0.7), and hopefully this will be the final fix on this matter :)
