### ISSUE TITLE
Plugin Initialization Failed

### ISSUE THREAD

**Issue by alexeiryn** [easly1989/ffxiv_act_dfassist#19]
DF assist hasn't been working properly for a couple days now with toasts, but it was at least loading. As of updating ACT though, I'm getting

Plugin Initialization Failed
Cannot create a file when that file already exists.

I tried removing all the files in my roaming data, and fresh installing from Releases into my ACT folder, but neither have fixed it. I'm not even sure which file is already existing that can't be updated, since it gives me no further explanation.

**Comment by easly1989** [comment]
The problem is related to issue #16 
The workaround is to delete the Default.log file, located in your ACT/logs folder.

I'm sorry for the inconvenience, I'm working on a solution right now.

**Comment by easly1989** [comment]
Please try version 2.0.3, and if the problem persist write here again, and reopen the issue
