### ISSUE TITLE
"Could not find Duty with 0, report to the dev!" error

### ISSUE THREAD

**Issue by alexeiryn** [easly1989/ffxiv_act_dfassist#22]
The plug-in seems to mostly still be functional, but I'm getting that + a slider tray error(???).

![image](https://user-images.githubusercontent.com/40779912/64594392-8b1bcc80-d375-11e9-9348-f0d73f7fb3f1.png)

Still seems to work okay and report the correct duties so it's probably low priority, but since it explicitly said to report it, there you go.

**Comment by easly1989** [comment]
2.0.4 resolvd the Error about the trayslider, be sure to update your version of DFAssist
I'll work on a fix for the Duty 0 warning too for next release 

Thank you for reporting! (:
