### ISSUE TITLE
"If you see this...." toast no longer shows on startup

### ISSUE THREAD

**Issue by xeropresence** [easly1989/ffxiv_act_dfassist#23]
If i toggle "disable toasts" the toast gets displayed but when starting act up it doesn't get displayed anymore.

**Comment by easly1989** [comment]
Yep i removed it on startup, as for me it was annoying (like also the TTS if it was enabled ^^)
you think it was nice "feature"? 
I may add a "check toast" button to see if those works (but just disabling and enabling or changing them from ACT to Windows should show the test toast normally)

**Comment by xeropresence** [comment]
I thought it was annoying but useful lol, it not appearing was a big part of why I found the plugin wasn't loading correctly. Also you should update the readme as it mentions that toast.

**Comment by easly1989** [comment]
I'll update the README and work on a button to test the active configuration

**Comment by easly1989** [comment]
All done in 2.0.6
Not really "visible" as the toast that was appearing at every ACT startup, but it is something to test out the configuration at least :P
