### ISSUE TITLE
Missing duty names

### ISSUE THREAD

**Issue by xeropresence** [easly1989/ffxiv_act_dfassist#24]
Did you manually create the json files or did you write a tool to create them?

**Comment by easly1989** [comment]
I usually grab them from the official DFAssist app (from which i forked back in the day)
[https://github.com/Jaehyuk-Lee/DFAssist](https://github.com/Jaehyuk-Lee/DFAssist)

And modify the file according to my needs (i don't use the FATE and macroes)

so yeah, in the end most of the work is done manually ^^'
