### ISSUE TITLE
Not working because of 5.1 patch

### ISSUE THREAD

**Issue by evanoktavians** [easly1989/ffxiv_act_dfassist#31]
5.1 patch broke DF Assist. Fixes are much appreciated!

**Comment by DarkDestry** [comment]
The network offsets have been changed in the new patch

**Comment by DAOWAce** [comment]
o/

Hope it can updated soon.  Running in roulettes blind is awful!

**Comment by xeropresence** [comment]
Fixed with https://github.com/easly1989/ffxiv_act_dfassist/pull/32

**Comment by easly1989** [comment]
Merged the changes from @xeropresence 
closing this :)

**Comment by DAOWAce** [comment]
Not fixed.
