### ISSUE TITLE
Discord support?

### ISSUE THREAD

**Issue by sleepiebye** [easly1989/ffxiv_act_dfassist#33]
I know there's a different dfassist with discord support already, but do you have any plans for discord support in the future? I find using your ACT version much more comfortable T-T
(Thank you for your hard work)

**Comment by easly1989** [comment]
At the moment I don't have much time to dedicate to this plugin, unfortunately.
I've added a collaborator, in the hope that this project will continue forth (@xeropresence)

So, for the moment I would say, it is something that will be added, but if it should depends only on me, there would be no ETA

**Comment by sleepiebye** [comment]
Okies. Thank you for taking the time to answer and have an awesome day!

**Comment by easly1989** [comment]
I've some spare time atm, and I was looking at how Discord works.
So, my question is:
- When you ask for "Discord Support" what do you mean exactly?

In fact I could implement a discord "access" and send message to a channel (all should be customizable from within the plugin, but you should also provide your discord password)
Or I should create a bot, and speak with that bot (and the bot would write the message in the channel you registered it to)

Honestly are both quite difficult to implment (at least for me, as a newbie on the matter)
Anyway, i'll wait for your suggetion :)

**Comment by sleepiebye** [comment]
Wow thank you for taking this into consideration. I was thinking of the user providing the bot token  (channel/server id if required) and that bot sending the message but if this is difficult your first solution of providing "access" sounds great too! Sorry and thank you!

**Comment by easly1989** [comment]
I'll take this into consideration, and anyway still no ETA on when this feature will be available...
... but I'm working on it :P

**Comment by easly1989** [comment]
@sleepiebye So, I had a little bit of time to investigate more, so hear out my possible solutions (and some questions too):
1. it would be possible to use a Webhook instead of a Bot (this should be much simplier)
2. It should be doable using a local bot (as I don't have the possibility to host a bot anywere else unfortunately)

The downside of (1) is that it simply prints out a message in a defined channel (no DM possibility, and no tagging afaik)
The downside of (2), being a local bot, is that it may have several problem when multiple ppl tries to use it at once (honestly I don't even know if multiple ppl can actually run the client for the bot, i was not able to try).

So we get to the question:
- Usually how would you get this notification? (DM, message in a group channel or in a private channel, your username gets tagged?)

waiting your feedback (:

**Comment by sleepiebye** [comment]
If it's a local bot hosted by the user's computer or webhook with no tag, I would think a message in a private channel would be best (and no need to tag user then). If it has to be a group channel, there probably is a need for user tag to mute the rest of the messages. Hope this helps?

**Comment by easly1989** [comment]
Yep it surely helps.
With the webhook should be possible to send message to your desired channel (private or not)
Anyway i'll try it when i can to ensure that (and avoid bloating the plugin with an enire bot)

**Comment by xeropresence** [comment]
I'm concerned about feature creep. There's already a bevy of methods for notification. Does every thing really need discord?

**Comment by sleepiebye** [comment]
It's not needed if it's bloating the plugin T-T I just mentioned it because I didn't use the other message apps and usually lots of gamers use discord during game play;; Sorry for this

**Comment by easly1989** [comment]
Well, most of the notification methods can be considered optional, so why not i would say?
If we can keep it simple enough, it would be reduced to a flag and a check before a webapi call (using webhooks), and make the users happy (:

**Comment by easly1989** [comment]
In [2.2.3](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.2.3) I've enable the Discord Support.
It needs a lot of testing, but I don't have time now to test it (it is another thing that is blocked in my work network... >.<)
So @sleepiebye or anyone else that wants to try it, please let me know if it works, or if there are any problems while settings up or anything

Thank you! :)

(ps. in the case that it works I may to start writing the wiki to use the plugin, it may come handy for all the feature and settings it has)

**Comment by sleepiebye** [comment]
So far so good!
By username you mean the bot's name right? That's what I put in and it works so @~@;;
Thank you so much for this!!

**Comment by easly1989** [comment]
well, it was supposed to be "your" username, and it should be used like this:
@{username} "{title}\n>>>>> {message}

Most probably it will simply ignore it and just push a notification (i suppose? ... ^^')
anyway, it would be really kind of you to write the steps you followed to make it work, so that i can put it in the wiki (for others to use!)

**Comment by sleepiebye** [comment]
1. Choose/create the discord server that will host your alarm bot.
2. Click on the arrow besides the server name.
![1](https://user-images.githubusercontent.com/57329885/68760154-941a6a00-0654-11ea-8b41-18aabff673ce.png)
3. Choose _Server Settings_.
![2](https://user-images.githubusercontent.com/57329885/68760186-a5fc0d00-0654-11ea-9240-80ddc6420cd3.png)
4. Click on _Webhooks_ then _Create Webhook._
![3](https://user-images.githubusercontent.com/57329885/68760295-d93e9c00-0654-11ea-85e6-24b089e61b91.png)
5. Enter name of bot and change channel if needed. Copy link below then save.
![4](https://user-images.githubusercontent.com/57329885/68760360-025f2c80-0655-11ea-8ead-8ebc73158870.png)
6. Go to ACT and enter the link copied to Webhook URL, and Username(or whatever you want to be called).
7. Click test to see if everything is working.
DONE!

**Comment by sleepiebye** [comment]
@easly1989 Username doesn't show up on discord message, so might not need it?
This is what I received.

Duty Found!
> > > > >  The Copied Factory

**Comment by easly1989** [comment]
I'll add the username to the message too, with the "@" to ensure it calls out to the right person
Thank you for the mini-tutorial, really appreciated :)
