### ISSUE TITLE
Plugin loading, but not working.

### ISSUE THREAD

**Issue by Handekmoo** [easly1989/ffxiv_act_dfassist#34]
When I started up the plugin, it tells me my settings, downloads and updates localizations, updates UI and tells me the plugin has started and has connected to a network packet, but that's all it does. Queueing for a duty, it doesn't register any queue of any sort. When I test my settings the toast works, the flashing taskbar icon works, TTS works. I'm on Windows 10.

This is my log

> [05:18:50] Plugin Init
>[05:18:50] Plugin Version: 2.0.9.0
>[05:18:50] Settings Loading...
>[05:18:50] Language: English
>[05:18:50] Disable Toasts: False
>[05:18:50] Make Toasts Persistent: True
>[05:18:50] Enable Legacy Toasts: True
>[05:18:50] Enable Text To Speech: False
>[05:18:50] Enable Test Environment: False
>[05:18:50] Enable Telegram Notifications: False
>[05:18:50] Enable Pushbullet Notifications: False
>[05:18:50] Settings Loaded!
>[05:18:50] Updating Localization files from web...
>[05:18:50] Downloading en-us file
>[05:18:50] Updated en-us file
>[05:18:50] Downloading fr-fr file
>[05:18:50] Updated fr-fr file
>[05:18:50] Downloading ja-jp file
>[05:18:50] Updated ja-jp file
>[05:18:50] Downloading ko-kr file
>[05:18:50] Updated ko-kr file
>[05:18:50] Localization files update completed
>[05:18:50] Updating data files from web...
>[05:18:50] Downloading en-us file
>[05:18:50] Updated en-us file
>[05:18:50] Downloading fr-fr file
>[05:18:50] Updated fr-fr file
>[05:18:50] Downloading ja-jp file
>[05:18:51] Updated ja-jp file
>[05:18:51] Downloading ko-kr file
>[05:18:51] Updated ko-kr file
>[05:18:51] Data files update completed
>[05:18:51] Changing language to en-us...
>[05:18:51] Language changed to en-us
>[05:18:51] Updating data for language en-us...
>[05:18:51] UI: Data updated to v20191030.1 for en-us
>[05:18:51] Data 20191030.1 Initialized!
>[05:18:51] Updating UI...
>[05:18:51] UI Updated!
>[05:18:51] Plugin Started!
>[05:18:51] P: FFXIV Process Selected: 13224
>[05:18:51] N: Starting Network Reading...
>[05:18:51] N: Detected Game Server Connection: 192.168.1.71:49678 -> 204.2.229.109:55028
>[05:18:51] N: Detected Game Server Connection: 192.168.1.71:49679 -> 204.2.229.109:55028
>[05:18:51] N: Local EndPoint Found: 192.168.1.71
>[05:18:52] N: Started Reading Network Packets
>[05:18:52] Plugin Enabled

This is after starting it with 14 already open and logged in.

I've tried with and without my VPN, ACT plugin load order in every configuration, starting ACT first. Starting ACT after logging into the game(not on character selection, actually in the game world.) Uninstalling and reinstalling while the game is both running and not running. Test environment on and off. I can't figure out what's wrong.

**Comment by easly1989** [comment]
On your side it all seems correct, at least reading the logs 
The problem seems to be related mostly to the server packets not being read.
There was another issue regarding problems with packets not getting read if behind a VPN.

I'll try to investigate when I can.

**Comment by Handekmoo** [comment]
Take your time. I just can't for the life of me figure out what could be blocking it. I've entirely shut down any VPN I have and it still doesn't work.

**Comment by easly1989** [comment]
Just to know, using [this tool here](https://github.com/Jaehyuk-Lee/DFAssist/releases/download/v20191003.1/DFAssist.v20191003.1.zip) is it working ok?
(this is the standalone version of this plugin, that works without using ACT;
I'm starting to think that the problems related to the network issues may be connected to ACT itself)

**Comment by Handekmoo** [comment]
Just tried that, doesn't work. I would assume that could mean it's an issue on my end, right?

**Comment by easly1989** [comment]
It may or may not be actually.
The way the code is written to read packets is not the best, and has some flaws.

You may want to try out something (dunno what tbh), as for the most majority of the users it is working ok.

Anyway, I'm trying to use the ravahn Machine packet handler, it should work out of the box and solve all the flows we actually have right now (hopefully).

It will take some time, so don't hold your breath :P
I'm sorry for the inconvenience,

I'll keep you updated as soon as I've any news ;)

**Comment by easly1989** [comment]
So, I did a quick and dirty implementation using the ravanh machina packet handler
It is still an alpha, and I'm unable to test it with FF (as I'm at work)

So, give this a try and let me know if it works, crashes or whatever... XD
I'll wait for your feedback!

[DFAssist_2.1.0_machina_pre.zip](https://github.com/easly1989/ffxiv_act_dfassist/files/3804608/DFAssist_2.1.0_machina_pre.zip)

**Comment by QT-M** [comment]
The stand alone does not work. Please note patch 5.1 changed how network packet information. ACT works because they fixed the ffxiv plugin.

**Comment by easly1989** [comment]
Yep, that is why i tried using the ravahn machina network packethandler, it should be updated and compliant with the newest patch

**Comment by amparagas** [comment]
I tried out the alpha version. 
There isn't any console messages regarding: Game Server Connection, Process, Local Endpoint being found, and reading network packets.

I tested by just queueing into a Trust Dungeon and there's no information in console regarding the duty.

**Comment by DAOWAce** [comment]
2.1.0 is not working for me either.

Doesn't even say it's network connected like the non-alpha plugin.

Guess it's back to using XIVLauncher in the interim..

**Comment by Handekmoo** [comment]
Yeah. Can confirm as everyone else that one isn't working. Does the same thing as the original release when ACT is open and logging into the game, but when I start ACT with the game running, it doesn't connect to a packet at all.

**Comment by easly1989** [comment]
i'll look back into it,
the lack of logging was due to the code not being mine anymore (as i said I used the code from ravahn)
Anyway, i'll keep you updated as soon as i've news!

**Comment by easly1989** [comment]
[Version 2.1.1](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.1.1) should address the problem;
As I've read on other repo the opcodes should all be right, but there was a control to avoid cluttering of packets (so the code to analyze the packets was executed only for certain opcodes)

you can check the changes [here](https://github.com/easly1989/ffxiv_act_dfassist/commit/dde301a9736e3721f96ceaeb407d8347e1c67d72);

That if was completely wrong, and was discarding almost every packet received.
So, if that was the problem, it should be fixed.

Let me know!

**Comment by Handekmoo** [comment]
It works! It gives some strange errors in the log, and the toasts aren't working, but TTS works and it shows the dungeon as shown in the image of my log. It may have something to do with the fact I'm just using a trust dungeon to test though.

![image](https://user-images.githubusercontent.com/57315982/68215584-7f333c00-ffad-11e9-88e9-17d7b4472d99.png)

**Comment by easly1989** [comment]
I'm working on that one, noticed a couple of misbehaviors regarding the notifications.
Actually the "Unable to find the string Duty Found!" is really strange ..XD... i'll investigate on it too :)

As a minor bug, i think this issue can be closed,
Thank you for the report and testing :)
