### ISSUE TITLE
Unable to show toast notification

### ISSUE THREAD

**Issue by haojunsui** [easly1989/ffxiv_act_dfassist#37]
UI: Unable to show toast notification: Cannot load DLL“DFAssist.WinToast.dll”: Cannot find specific module.

**Comment by easly1989** [comment]
This may be related to #36..
Anyway i would suggest you to try and make a clean install (downloading the plugin from here, or using the integrated plugin download inside ACT)

The problem you have is that the assembly. Load for some reason is unable to locate the file, that should be placed under libs/

Anyway, I'll also give a look to the content of the latest release, zip file (if for any reason that file was missing.. 😅)

**Comment by easly1989** [comment]
Checked the zip file, and everything is in the right place..
Please give [2.1.4](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.1.4) a try and let me know if you still have the same problem!

**Comment by lockejj** [comment]
This issue only happens to me in 2.1.4 and 2.1.5, 2.1.3 works and shows the toast notification correctly. I have removed all files and freshly put them in to ACT to test and only 2.1.3 works for me at the moment for toast. Otherwise I get the error referenced above. All files are in the same place it looks like for each but it just fails to load the module if it's not 2.1.3

**Comment by HeliosXII** [comment]
I'm having the issue too, except in my case 2.1.3 doesn't work either. I get the same error message in the log, although mine has a little extra bit that I'm not sure if OP just omitted or if that part doesn't show up for them.

> [13:43:31] UI: Unable to show toast notification: Unable to load DLL 'DFAssist.WinToast.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by haojunsui** [comment]
Adding more detail on the problem here. pre-2.1.3 has toast working correctly. Same as @HeliosXII , the error started to appear from 2.1.3. All installs were done through removing entire DFAssist folder and unloading dll from ACT, and reinstalling. The op code was omitted as they were different every time.

**Comment by Kumicoo** [comment]
Same error. DFAssist.WinToast.dll' bla bla

**Comment by easly1989** [comment]
[2.1.6](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.1.6) should solve this issue, closing
(consider reopening/writing again in this issue, in case you still get the problem)
