### ISSUE TITLE
Error loading DFAssistWinToast.DLL

### ISSUE THREAD

**Issue by lancemate** [easly1989/ffxiv_act_dfassist#39]
Still getting this error on 2.1.6

[10:28:38] UI: Unable to show toast notification: Unable to load DLL 'libs/DFAssist.WinToast.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Tried clean install, files definitely not blocked, DLL in correct \libs folder.

**Comment by easly1989** [comment]
just noticed, really strange, using it with visual studio attached works perfectly lol...
I'll investigate more on the matter,

sorry about the inconvenience :(

**Comment by easly1989** [comment]
[2.1.7](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.1.7) should address this issue, 
i'll leave this open (just in case), while waiting for a positive feedback

**Comment by HeliosXII** [comment]
> [07:07:48] UI: Unable to show toast notification: Unable to load DLL 'DFAssist.WinToast.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I'm still getting this, unfortunately. I did notice, however, that the version still says 2.1.6 even though I triple checked I was downloading the 2.1.7 release and got rid of all the old files first. I dunno if I did something wrong, if something's still wonky with the 2.1.7 release, or if maybe you just overlooked updating the version number or something.

**Comment by easly1989** [comment]
Most probably something went wrong when building the file oO... 
i'll push a new version (2.1.8) and test it again to ensure it works;

i'll report back here!

**Comment by easly1989** [comment]
Hopefully [this should work](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.1.8) 

when using the plugin, try testing it first.
you should see a log with the full path to the directory where the dll files should be locates, like this:
- [14:10:29] UI: Toast library path: C:\Users\easly1989\source\repos\ffxiv_act_dfassist\Release\libs

for me it solved the problem when running act not attached to visual studio,
let me know if for you is the same

**Comment by lancemate** [comment]
Still no joy on 2.1.8 :(

Ran test and got the correct path:
[14:38:29] UI: Toast library path: C:\Apps\Advanced Combat Tracker\DFAssist\libs

**Comment by HeliosXII** [comment]
Ditto, still not working. The path looks right, but I'm still getting the same error as I posted above.

> [08:42:32] UI: Toast library path: C:\Final Fantasy XIV\ACT\plugin\DFAssist Plugin\libs

**Comment by easly1989** [comment]
oh boy... 
ok, i'll take the time to fix it properly, sorry about that!

gonna pin this issue, and work just on this until we have a stable and working solution.

**Comment by easly1989** [comment]
Can you give a try to [2.2.0](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.2.0) and tell me if you still receive the error in the DFAssist log?
(i''ve left the fallback toast method, so in any case it should work, but i really would like to make it work correctly ^^')

If you are still receiving the error I may consider dropping the wintoast project and refence the UWP libraries to show the toasts as I want...

...so, i'll wait for your feedback :)

**Comment by Kyojuni** [comment]
Hi, i have the problem too ^^"
i've tested three times
i'm using 2.2.0 version

and here is the error :
> [11:04:15] UI: Unable to use DFAssist.WinToast, using built in notifier...: Impossible de charger la DLL 'DFAssist.WinToast.dll': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)

here is the screenshot : 
[https://gyazo.com/e87292b16422027c59fd1e1ba4ecfd89](url)

(i have an another problem, i will open a new issue ticket for that)

**Comment by easly1989** [comment]
Yeah, this is one of those problems I'm really unable to understand.. So, I'm working on removing that library and using the windows uwp one, that is integrated with windows

**Comment by easly1989** [comment]
in [2.2.1](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.2.1) i've removed that c++ library, now DFAssist is using the windos 10 UWP library to show toasts.
As a side, i've left the NotifyIcon fallback, so that in any case a toast should be shown up.

this problem should not be present anymore (As that library has been removed completely)
let me know if you still have problems btw, if not close the issue!

**Comment by HeliosXII** [comment]
The problem does indeed seem to be resolved for me with 2.2.1! Thanks for your hard work!

**Comment by Kyojuni** [comment]
Notifications are working without errors ! ^^
Problem solved x)
Thank you Easly1989 for the update and your hard work on this plugin ^-^
