### ISSUE TITLE
Could not find Duty

### ISSUE THREAD

**Issue by Kyojuni** [easly1989/ffxiv_act_dfassist#41]
Hi, the plugin is giving me an error when i tag with the DF

error : 
> [10:44:55] Q: Matched [6 - Mission aléatorie: défis] - [134 - Unité de contention S1P7]
> **[10:44:59] Could not find Duty with 14851, report to the dev!**
> [10:44:59] Q: Matching State Updated [Unknown Duty (14851) - Tanks: 0/0, Healers: 1/0, Dps: 2/0]

On the first line it seems like he found it but the second line say that there is an error

Screenshot :
[https://gyazo.com/3c184c30ffe8d995d97dd43dec0e9cfe](url)

**Comment by Kyojuni** [comment]
UPDATE : As you can see he found the good one, but in the log there is this weird red error, even if the first line say the name of the Duty

Screenshot :
[https://gyazo.com/00b491aeb304d398e82fc0272466c04e](url)

**Comment by easly1989** [comment]
Most probably a miss-coded behavior in the update matching state packet,
and I'm looking for the wrong bytecode.
I'll look into it when i can, thank you for reporting (:

**Comment by easly1989** [comment]
[2.2.1](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.2.1) should solve the issue, 
in that case please close this issue, otherwise let me know :)

**Comment by Kyojuni** [comment]
The error is no more here !
Thank you for the update/fix Easly1989 ^-^
