### ISSUE TITLE
5.11 broke plugin

### ISSUE THREAD

**Issue by sleepiebye** [easly1989/ffxiv_act_dfassist#43]
Seems like the new patch broke the plugin.
Heard the numbers for the duties were all changed this patch over at ACT discord OTL;;

[11:43:12] Could not find Roulette with 128, report to the dev!
[11:43:12] Q: Duty Roulette Matching Started [128] - Unknown Roulette (128)

**Comment by easly1989** [comment]
Should be working in [2.2.3](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.2.3)
If you are able to test it (and it works), you can close the issue

otherwise, let me know :)

**Comment by sleepiebye** [comment]
Yup working as of 2.2.3
Wow hope they don't change the coding? or whatever it is every time and give developers headaches.
Closing this and thank you!
