### ISSUE TITLE
Discord notification is not sent in Japanese

### ISSUE THREAD

**Issue by FFFFFF66** [easly1989/ffxiv_act_dfassist#49]
Notifications are not sent to discord only if the language setting is Japanese.
This can send notifications correctly to discord just by changing the language to another language

**Comment by easly1989** [comment]
Very strange, tomorrow i'll look into it!
(even if the code is actually the same, and should not be dependent on the ui language)

i'll keep you updated ;)

**Comment by easly1989** [comment]
Could you please do a clean install and try version [2.2.8](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/2.2.8)?
(I have changed the library used to run the webhook, and this may solve your problem)

let me know!
