### ISSUE TITLE
Logging not accurate

### ISSUE THREAD

**Issue by Nypheena** [easly1989/ffxiv_act_dfassist#5]
Sometimes I miss the toast and it isn't saved in w10 notifications so if I go to check logs all I see is Sastasha on everything.
https://i.imgur.com/83a12SA.png

**Comment by easly1989** [comment]
Just to be sure.
When you "get to see" the toast, it shows the correct dungeon/trial/raid?
So, only the log is showing the wrong one?

(I'm asking as I cannot test it right now, as I'm at work!)

Beside that, I'll for sure try to make the taost more "permanent" (with a setting from the ACT interface maybe)

Thank you for pointing out the issue :)

**Comment by easly1989** [comment]
@ZeroMaki The problem should be solved in latest release.
If you can try it and report back it would be awesome :)

--- edit
Sorry, closed the issue by mistake ^^'

**Comment by Nypheena** [comment]
Hi, sorry didn't manage to respond fast enough, yes the toast is correct it was only the log that was inaccurate and it works now, I got Syrcus tower and the log reflected that thank you so much for the fix <3 love the plugin

**Comment by easly1989** [comment]
Nice! :)

**Comment by Nypheena** [comment]
https://i.imgur.com/L8DEaI1.png the accepted status seems to be inaccurate too but thats a minor thing, just figured I'd let you know

**Comment by easly1989** [comment]
I see, honestly that is something I took from the devunt branch when i forked,
but not something I really wanted to mantain (as for me, it is only usefull to see what is the dungeon that is going to start, and all the other informations are not so important.)

If it is not a highly requested feature (and I really hope so),
I'll probably simply remove it (making the code even a bit more reliable, not raising all those unneeded events!)

**Comment by Nypheena** [comment]
Personally I think its useless I mean you can see it right in the game, the useful part is the notifications and seeing which one you got in roulette. So I'd be 100% behind removing it =)
