### ISSUE TITLE
TTS always talks when opening ACT

### ISSUE THREAD

**Issue by GracefulUni** [easly1989/ffxiv_act_dfassist#53]
I updated to the new release that was a hour or ago or something, this is my first time setting this up btw.
I have the "enable TTS"
but everytime i open ACT it always says "if you hear this, TTS works"
Not sure if this is intentional but would there be a way for that not happen when i open ACT all the time? I can disable TTS but it be nice to hear TTS when a duty or w.e pops up lol

**Comment by easly1989** [comment]
I'll disable the check on startup asap
Is something i want to do from some time, just always had something else to do 😅

**Comment by GracefulUni** [comment]
> I'll disable the check on startup asap
> Is something i want to do from some time, just always had something else to do 😅

Lol its alright, thanks!

**Comment by easly1989** [comment]
2.2.10 solves this issue
