### ISSUE TITLE
No status on plugin

### ISSUE THREAD

**Issue by FeeblePepe** [easly1989/ffxiv_act_dfassist#58]
So I downloaded the update unblocked the zip and extracted to a new folder. I ran the dll on plugins but getting a no status on act and DFassist tab is completely blank

**Comment by FeeblePepe** [comment]
After Deleting the folder and redoing the install it now runs and no errors present but when DF pops no notifications come up not even tts

**Comment by easly1989** [comment]
this must be related to the opcodes
#52 , unfortunately I'm not able to check this on my own as the square is working hard to (apparently) shut down this kind of plugins..

Anyway, you can check issue #52 to have updates on the matter
