### ISSUE TITLE
Unhandled Exception in ACT

### ISSUE THREAD

**Issue by Dysfonction** [easly1989/ffxiv_act_dfassist#59]
Hey, got an error while trying to use the latest version of DFAssist

https://imgur.com/a/whplw4W

I'm not sure how to fix it, I tried to disable some other plugins but it stays the same

**Comment by easly1989** [comment]
One of the other plugin you are loading is using an old versione of Discord.NET.Webhook DLL.
You should try to disable every other plugin except FFXIV_ACT_Plugin and DFAssist and it should work.
If I recall ok it was Hojoring or TTS Yukkiri that was causing the problem
