### ISSUE TITLE
Opcode Wizard

### ISSUE THREAD

**Issue by ffxivvillein** [easly1989/ffxiv_act_dfassist#60]
https://github.com/karashiiro/FFXIVOpcodeWizard

Can I find duty opcode automatically like this?
I want to add korean server opcode.

**Comment by easly1989** [comment]
You can try using that tool and check the various opcode you receive when doing your queues and when matching.
Then you can report them back here, or do a test on a fork and them do a pullrequest if it is working for you ;)
