### ISSUE TITLE
Stopped working since last ffxiv update

### ISSUE THREAD

**Issue by morpheus305** [easly1989/ffxiv_act_dfassist#61]
Was working before but no longer.

**Comment by CFTiffers** [comment]
That's normal when the game is patched, especially as we've had a new duty added. Give him a chance to update it.

**Comment by easly1989** [comment]
All the discussions regarding updates and possible solutions on opcodes changing on every patch can be found here #52 
Closing this, but thank you for your issue contribution ;)
