### ISSUE TITLE
Version 1.5.0 prevent Triggernometry from loading

### ISSUE THREAD

**Issue by ghost** [easly1989/ffxiv_act_dfassist#9]
ACT 3.4.0 Release 260
DFAssist 1.5.0
FFXIV_ACT_Plugin 2.0.2.7
Triggernometry 1.0.9.1
OverlayPlugin 0.3.7.0

![image](https://user-images.githubusercontent.com/43957601/61966094-014db500-affc-11e9-93a3-1dff025a2ab6.png)

When I disable DFAssist Triggernometry will load successfully

![image](https://user-images.githubusercontent.com/43957601/61966148-26422800-affc-11e9-8fc3-4edae43a8b18.png)

**Comment by easly1989** [comment]
Noticed.
The strange thing is that the error gets triggered by Triggernometry (so I can't actually debug it)

I suppose it is connected to some event handing i do that triggers thing in that plugin too for some reason.

As soon as I get home I'll investigate and report back!

Sorry for the inconvenience 😣

**Comment by easly1989** [comment]
I have tested multiple time, with the same exact version you have of Triggernometry and I'm unable to reproduce the problem.

I'm unable to debug having triggernometry as a plugin (but that happens even if I don't have DFAssist on..)

![immagine](https://user-images.githubusercontent.com/3910202/61993337-a1422780-b06a-11e9-8794-053b1907b87d.png)

I'll leave this open;
But it may be something to debug/understand with the help of @paissaheavyindustries

**Comment by ghost** [comment]
Currently using updated DFAssist version 1.5.1

After i saw your plugin load order, i tried that order. it works. i load DFAssist after FFXIV_ACT_Plugin.

![image](https://user-images.githubusercontent.com/43957601/61994102-63f88c80-b0a0-11e9-9fca-810a39934375.png)

when i put DFAssist before FFXIV_ACT_Plugin the error comes back.

**Comment by easly1989** [comment]
How did i not noticed that!? 😵
Anyway, I dunno if it is a common thing for all the plugins.. But DFAssist needs the FFXIV plugin to be installed first.

For this reason I'll add a check, and prevent the plugin from loading if it doesn't find the parsing plugin first!

**Comment by ghost** [comment]
Usually I load everything after FFXIV_ACT_Plugin. I loaded DFAssist first because I was following frontpage guide.

![image](https://user-images.githubusercontent.com/43957601/61994430-488f8080-b0a4-11e9-857b-e03518b93506.png)

I'm glad it works now. Thank you for your help

**Comment by easly1989** [comment]
> 
> 
> Usually I load everything after FFXIV_ACT_Plugin. I loaded DFAssist first because I was following frontpage guide.
> 
> ![image](https://user-images.githubusercontent.com/43957601/61994430-488f8080-b0a4-11e9-857b-e03518b93506.png)
> 
> I'm glad it works now. Thank you for your help

Yeah, I have to update the front page, as the ACT is now updated
In the older version of it, the plugin were loaded from bottom to top.
Now it seems that they are loaded from to bottom ^^'...

Anyway, glad that the issue was addressed,
Have fun :)
